# Generated by Django 3.2.7 on 2021-09-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=45)),
                ('study', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'lang',
                'managed': False,
            },
        ),
    ]
