# Generated by Django 3.2.7 on 2021-09-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0002_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jinmae',
            fields=[
                ('코드', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('제품명', models.CharField(max_length=40)),
                ('브랜드', models.CharField(max_length=20)),
                ('제품상세분류', models.CharField(max_length=20)),
                ('number_1회제공량', models.IntegerField(db_column='1회제공량')),
                ('에너지_kcal_field', models.IntegerField(db_column='에너지(Kcal)')),
                ('단백질_g_field', models.IntegerField(db_column='단백질(g)')),
                ('지질_g_field', models.IntegerField(db_column='지질(g)')),
                ('탄수화물_g_field', models.IntegerField(db_column='탄수화물(g)')),
                ('총당류_g_field', models.IntegerField(db_column='총당류(g)')),
                ('나트륨_mg_field', models.IntegerField(db_column='나트륨(mg)')),
                ('콜레스테롤_mg_field', models.IntegerField(db_column='콜레스테롤(mg)')),
                ('총_포화_지방산_g_field', models.IntegerField(db_column='총 포화 지방산(g)')),
                ('트랜스_지방산_g_field', models.IntegerField(db_column='트랜스 지방산(g)')),
            ],
            options={
                'db_table': 'jinmae',
                'managed': False,
            },
        ),
    ]
